# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 94c265e8ba8882f384a0b79e809f659cceb9cba26317196d17e61b9b1668b7df161281efc1b77c95d170b2195d2a2e0cca5862e49bd3597f5abd46d6ab2f7da4

test:
  secret_key_base: dabf22a95170b329a7f87160e7cff2cfde7dec670e306806fb3f23ebeab63d9da9ffa48add2af237f09a71cedf0b6d604a6c7d08fd74cb64d5c3f973880cc317

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
